--Creating table for orders

CREATE TABLE orders(
	order_id INT NOT NULL PRIMARY KEY,
	order_date DATE NOT NULL,
	order_time TIME NOT NULL
)

SELECT * FROM orders;


--Creating table for Pizzas

CREATE TABLE pizzas(
	pizza_id VARCHAR(100) NOT NULL PRIMARY KEY,
	pizza_type_id VARCHAR(100) NOT NULL,
	pizza_size VARCHAR(10) NOT NULL,
	pizza_price NUMERIC(10, 2)
)

SELECT * FROM pizzas;


--Creating table for Pizza types

CREATE TABLE pizza_types (
    pizza_type_id VARCHAR(50) PRIMARY KEY,
    pizza_name VARCHAR(100) NOT NULL,
    category VARCHAR(50) NOT NULL,
    ingredients TEXT NOT NULL
);


SELECT * FROM pizza_types;


--Creating table for Order Details

CREATE TABLE order_details(
	order_details_id INT NOT NULL PRIMARY KEY,
	order_id INT NOT NULL,
	pizza_id VARCHAR(100) NOT NULL,
	order_quantity INT NOT NULL
)

SELECT * FROM order_details;


--- NOTE: After creating the table, we have imported the data in created tables by using 'Import/Export data' option.


--- Below are the queries used to get the required business insights.


--- 1. Retrieve the total number of orders placed.

SELECT count(order_id) as Total_Orders FROM orders;



--- 2. Calculate the total revenue generated from pizza sales.

SELECT
	ROUND(
		SUM(ORDER_DETAILS.ORDER_QUANTITY * PIZZAS.PIZZA_PRICE),
		2
	) AS TOTAL_REVENUE
FROM
	ORDER_DETAILS
	JOIN PIZZAS ON ORDER_DETAILS.PIZZA_ID = PIZZAS.PIZZA_ID;



--- 3. Identify the highest-priced pizza.

SELECT
	PIZZA_TYPES.PIZZA_NAME,
	PIZZAS.PIZZA_PRICE
FROM
	PIZZA_TYPES
	JOIN PIZZAS ON PIZZA_TYPES.PIZZA_TYPE_ID = PIZZAS.PIZZA_TYPE_ID
ORDER BY
	PIZZAS.PIZZA_PRICE DESC LIMIT
	1;


--- 4. Identify the most common pizza size ordered.

SELECT
	PIZZAS.PIZZA_SIZE,
	COUNT(ORDER_DETAILS.ORDER_QUANTITY) AS QUANTITY_ORDERED
FROM
	PIZZAS
	JOIN ORDER_DETAILS ON PIZZAS.PIZZA_ID = ORDER_DETAILS.PIZZA_ID
GROUP BY
	PIZZAS.PIZZA_SIZE
ORDER BY
	QUANTITY_ORDERED DESC LIMIT
	1;


--- 5. List the top 5 most ordered pizza types along with their quantities.

SELECT
	PIZZA_TYPES.PIZZA_NAME,
	SUM(ORDER_DETAILS.ORDER_QUANTITY) AS QUANTITY
FROM
	PIZZA_TYPES
	JOIN PIZZAS ON PIZZA_TYPES.PIZZA_TYPE_ID = PIZZAS.PIZZA_TYPE_ID
	JOIN ORDER_DETAILS ON ORDER_DETAILS.PIZZA_ID = PIZZAS.PIZZA_ID
GROUP BY
	PIZZA_TYPES.PIZZA_NAME
ORDER BY
	QUANTITY DESC LIMIT
	5;


--- 6. Join the necessary tables to find the total quantity of each pizza category ordered.


SELECT
	PIZZA_TYPES.CATEGORY,
	SUM(ORDER_DETAILS.ORDER_QUANTITY) AS QUANTITY
FROM
	PIZZA_TYPES
	JOIN PIZZAS ON PIZZA_TYPES.PIZZA_TYPE_ID = PIZZAS.PIZZA_TYPE_ID
	JOIN ORDER_DETAILS ON ORDER_DETAILS.PIZZA_ID = PIZZAS.PIZZA_ID
GROUP BY
	PIZZA_TYPES.CATEGORY
ORDER BY
	QUANTITY DESC


---- 7. Determine the distribution of orders by hour of the day.

SELECT
	DATE_PART('hour', ORDER_TIME) AS HOUR,
	COUNT(ORDER_ID) AS ORDER_COUNT
FROM
	ORDERS
GROUP BY
	DATE_PART('hour', ORDER_TIME)
ORDER BY
	HOUR;

	

--- 8. Find the category-wise distribution of pizzas.


SELECT
	CATEGORY,
	COUNT(PIZZA_NAME) AS PIZZA_TYPE_COUNT
FROM
	PIZZA_TYPES
GROUP BY
	CATEGORY
ORDER BY
	PIZZA_TYPE_COUNT DESC;
	

--- 9. Group the orders by date and calculate the average number of pizzas ordered per day.

SELECT
	ROUND(AVG(QUANTITY), 0) AS AVG_PIZZA_ORDERED_PER_DAY
FROM
	(
		SELECT
			ORDERS.ORDER_DATE,
			SUM(ORDER_DETAILS.ORDER_QUANTITY) AS QUANTITY
		FROM
			ORDERS
			JOIN ORDER_DETAILS ON ORDERS.ORDER_ID = ORDER_DETAILS.ORDER_ID
		GROUP BY
			ORDERS.ORDER_DATE
	) AS ORDER_QUANTITY;



--- 10. Determine the top 3 most ordered pizza types based on revenue.

SELECT
	PIZZA_TYPES.PIZZA_NAME,
	SUM(ORDER_DETAILS.ORDER_QUANTITY * PIZZAS.PIZZA_PRICE) AS TOTAL_REVENUE
FROM
	PIZZA_TYPES
	JOIN PIZZAS ON PIZZA_TYPES.PIZZA_TYPE_ID = PIZZAS.PIZZA_TYPE_ID
	JOIN ORDER_DETAILS ON ORDER_DETAILS.PIZZA_ID = PIZZAS.PIZZA_ID
GROUP BY
	PIZZA_TYPES.PIZZA_NAME
ORDER BY
	TOTAL_REVENUE DESC
LIMIT
	3


--- 11. Calculate the percentage contribution of each pizza type to total revenue.

SELECT
	PIZZA_TYPES.CATEGORY,
	ROUND(
		SUM(ORDER_DETAILS.ORDER_QUANTITY * PIZZAS.PIZZA_PRICE) / (
			SELECT
				ROUND(
					SUM(ORDER_DETAILS.ORDER_QUANTITY * PIZZAS.PIZZA_PRICE)
				) AS TOTAL_SALES
			FROM
				ORDER_DETAILS
				JOIN PIZZAS ON PIZZAS.PIZZA_ID = ORDER_DETAILS.PIZZA_ID
		) * 100,
		2
	) AS PERCENT_REVENUE
FROM
	PIZZA_TYPES
	JOIN PIZZAS ON PIZZA_TYPES.PIZZA_TYPE_ID = PIZZAS.PIZZA_TYPE_ID
	JOIN ORDER_DETAILS ON PIZZAS.PIZZA_ID = ORDER_DETAILS.PIZZA_ID
GROUP BY	PIZZA_TYPES.CATEGORY
ORDER BY
	PERCENT_REVENUE DESC;



--- 12. Analyze the cumulative revenue generated over time.

SELECT
	ORDER_DATE,
	SUM(REVENUE) OVER (
		ORDER BY
			ORDER_DATE
	) AS CUM_REVENUE
FROM
	(
		SELECT
			ORDERS.ORDER_DATE,
			SUM(ORDER_DETAILS.ORDER_QUANTITY * PIZZAS.PIZZA_PRICE) AS REVENUE
		FROM
			ORDER_DETAILS
			JOIN PIZZAS ON PIZZAS.PIZZA_ID = ORDER_DETAILS.PIZZA_ID
			JOIN ORDERS ON ORDER_DETAILS.ORDER_ID = ORDERS.ORDER_ID
		GROUP BY
			ORDERS.ORDER_DATE
	) AS SALES



--- 13. Determine the top 3 most ordered pizza types based on revenue for each pizza category.

SELECT
	CATEGORY,
	NAME,
	REVENUE,
	RN
FROM
	(
		SELECT
			CATEGORY,
			NAME,
			REVENUE,
			RANK() OVER (
				PARTITION BY
					CATEGORY
				ORDER BY
					REVENUE DESC
			) AS RN
		FROM
			(
				SELECT
					PIZZA_TYPES.CATEGORY,
					PIZZA_TYPES.PIZZA_NAME AS NAME,
					SUM(PIZZAS.PIZZA_PRICE * ORDER_DETAILS.ORDER_QUANTITY) AS REVENUE
				FROM
					PIZZA_TYPES
					JOIN PIZZAS ON PIZZA_TYPES.PIZZA_TYPE_ID = PIZZAS.PIZZA_TYPE_ID
					JOIN ORDER_DETAILS ON ORDER_DETAILS.PIZZA_ID = PIZZAS.PIZZA_ID
				GROUP BY
					PIZZA_TYPES.CATEGORY,
					PIZZA_TYPES.PIZZA_NAME
			) AS A
	) AS B
WHERE
	RN <= 3;




















